# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: local
      hooks:
          - id: prettier
            name: prettier (local)
            entry: npx prettier --write
            language: system
            files: \.(js|jsx|ts|tsx|json|css|html|yaml|yml|vue|json)$
    - repo: local
      hooks:
          - id: eslint
            name: eslint (local)
            entry: npx eslint --fix --config=eslint.config.js
            language: system
            types: [file]
            files: \.[jt]sx?$
    - repo: local
      hooks:
          - id: check_keys
            name: Compare language keys
            entry: python3 .github/workflows/compare.py
            language: system
            types: [python]
